export const RealtimeSourceEventTypes = {
  GuestSessionCreated: 'GuestSessionCreated',
  GuestSessionRevoked: 'GuestSessionRevoked',
  GuestSessionUpgraded: 'GuestSessionUpgraded',
  ClubMemberContributionAdjusted: 'ClubMemberContributionAdjusted',
  ClubPointPoolAdjusted: 'ClubPointPoolAdjusted',
  ClubTreasuryAdjusted: 'ClubTreasuryAdjusted',
  ClubTitleAssigned: 'ClubTitleAssigned',
  ClubTitleCleared: 'ClubTitleCleared',
  ClubHonorAwarded: 'ClubHonorAwarded',
  ClubHonorRevoked: 'ClubHonorRevoked',
  ClubApplicationSubmitted: 'ClubApplicationSubmitted',
  ClubApplicationApproved: 'ClubApplicationApproved',
  ClubApplicationRejected: 'ClubApplicationRejected',
  ClubApplicationWithdrawn: 'ClubApplicationWithdrawn',
  ClubRankTreeUpdated: 'ClubRankTreeUpdated',
  ClubRecruitmentPolicyUpdated: 'ClubRecruitmentPolicyUpdated',
  ClubRelationUpdated: 'ClubRelationUpdated',
  ClubRelationChangeRequested: 'ClubRelationChangeRequested',
  PlayerBanned: 'PlayerBanned',
  PlayerEloChanged: 'PlayerEloChanged',
  ClubDissolved: 'ClubDissolved',
  SuperAdminGranted: 'SuperAdminGranted',
  TournamentAdminAssigned: 'TournamentAdminAssigned',
  TournamentAdminRevoked: 'TournamentAdminRevoked',
  TournamentLineupSubmitted: 'TournamentLineupSubmitted',
  TournamentSettlementRecorded: 'TournamentSettlementRecorded',
  TournamentSettlementFinalized: 'TournamentSettlementFinalized',
  TournamentClubInvited: 'TournamentClubInvited',
  TournamentPlayerInvited: 'TournamentPlayerInvited',
  TournamentLineupSelected: 'TournamentLineupSelected',
  TournamentTableStarted: 'TournamentTableStarted',
  MahjongTableStarted: 'MahjongTableStarted',
  MahjongTableReset: 'MahjongTableReset',
  MahjongTableRoundAdvanced: 'MahjongTableRoundAdvanced',
  MahjongTableArchived: 'MahjongTableArchived',
  TournamentAppealFiled: 'TournamentAppealFiled',
  TournamentAppealAdjudicated: 'TournamentAppealAdjudicated',
  AppealTicketFiled: 'AppealTicketFiled',
  AppealTicketAdjudicated: 'AppealTicketAdjudicated',
  AppealTicketReopened: 'AppealTicketReopened',
  AppealTicketWorkflowUpdated: 'AppealTicketWorkflowUpdated',
  Draw: 'Draw',
  Discard: 'Discard',
  Chi: 'Chi',
  Pon: 'Pon',
  Kan: 'Kan',
  Riichi: 'Riichi',
  DoraReveal: 'DoraReveal',
  Win: 'Win',
  DrawGame: 'DrawGame',
  AddedKan: 'AddedKan',
  ClosedKan: 'ClosedKan',
  OpenKan: 'OpenKan',
} as const;

export type RealtimeSourceEventType =
  (typeof RealtimeSourceEventTypes)[keyof typeof RealtimeSourceEventTypes];

export function isRealtimeSourceEventType(
  value: string,
): value is RealtimeSourceEventType {
  return Object.values(RealtimeSourceEventTypes).includes(
    value as RealtimeSourceEventType,
  );
}
