export enum RoundSettlementNote {
  ExhaustiveDraw = 'ExhaustiveDraw',
  AbortiveDrawRequested = 'AbortiveDrawRequested',
  TripleRonAbortiveDraw = 'TripleRonAbortiveDraw',
  DoubleRon = 'DoubleRon',
  TripleRon = 'TripleRon',
  NagashiMangan = 'NagashiMangan',
  Mangan = 'Mangan',
  Haneman = 'Haneman',
  Baiman = 'Baiman',
  Sanbaiman = 'Sanbaiman',
  Yakuman = 'Yakuman',
  DoubleYakuman = 'DoubleYakuman',
  TripleYakuman = 'TripleYakuman',
  QuadrupleYakuman = 'QuadrupleYakuman',
  QuintupleYakuman = 'QuintupleYakuman',
  SextupleYakuman = 'SextupleYakuman',
  SeptupleYakuman = 'SeptupleYakuman',
  OctupleYakuman = 'OctupleYakuman',
  NonupleYakuman = 'NonupleYakuman',
}
