export enum Permission {
  ViewPublicSchedule = 'ViewPublicSchedule',
  ViewClubDirectory = 'ViewClubDirectory',
  ViewPublicLeaderboard = 'ViewPublicLeaderboard',
  ViewOwnDashboard = 'ViewOwnDashboard',
  ViewClubDashboard = 'ViewClubDashboard',
  SubmitClubApplication = 'SubmitClubApplication',
  WithdrawClubApplication = 'WithdrawClubApplication',
  ManageClubMembership = 'ManageClubMembership',
  ManageClubOperations = 'ManageClubOperations',
  SetClubTitle = 'SetClubTitle',
  AssignClubAdmin = 'AssignClubAdmin',
  SubmitTournamentLineup = 'SubmitTournamentLineup',
  ManageTournamentStages = 'ManageTournamentStages',
  ConfigureTournamentRules = 'ConfigureTournamentRules',
  ResetTableState = 'ResetTableState',
  ManageTableSeatState = 'ManageTableSeatState',
  FileAppealTicket = 'FileAppealTicket',
  ResolveAppeal = 'ResolveAppeal',
  ManagePlatformOperations = 'ManagePlatformOperations',
  BanRegisteredPlayer = 'BanRegisteredPlayer',
  DissolveClub = 'DissolveClub',
  AssignTournamentAdmin = 'AssignTournamentAdmin',
  ViewAuditTrail = 'ViewAuditTrail',

}
