export type MahjongYakuKind =
  | 'KokushiMusouThirteenWait'
  | 'KokushiMusou'
  | 'PureChuurenPoutou'
  | 'ChuurenPoutou'
  | 'Tsuuiisou'
  | 'Ryuuiisou'
  | 'Chinroutou'
  | 'SuuankouTanki'
  | 'Suuankou'
  | 'Daisangen'
  | 'Daisuushi'
  | 'Shousuushi'
  | 'Suukantsu'
  | 'Tenhou'
  | 'Chiihou'
  | 'Chiitoitsu'
  | 'MenzenTsumo'
  | 'DoubleRiichi'
  | 'Riichi'
  | 'Ippatsu'
  | 'RinshanKaihou'
  | 'HaiteiRaoyue'
  | 'HouteiRaoyui'
  | 'Tanyao'
  | 'YakuhaiHaku'
  | 'YakuhaiHatsu'
  | 'YakuhaiChun'
  | 'RoundWind'
  | 'SeatWind'
  | 'Pinfu'
  | 'Ryanpeikou'
  | 'Iipeikou'
  | 'Toitoi'
  | 'Sanankou'
  | 'Sankantsu'
  | 'Shousangen'
  | 'SanshokuDoujun'
  | 'Ittsu'
  | 'Chinitsu'
  | 'Honitsu'
  | 'Honroutou'
  | 'Junchan'
  | 'Chanta'
  | 'SanshokuDoukou'
  | 'Dora'
  | 'AkaDora'
  | 'UraDora';

export const mahjongYakuLabels: Record<MahjongYakuKind, string> = {
  KokushiMusouThirteenWait: '国士无双十三面',
  KokushiMusou: '国士无双',
  PureChuurenPoutou: '纯正九莲宝灯',
  ChuurenPoutou: '九莲宝灯',
  Tsuuiisou: '字一色',
  Ryuuiisou: '绿一色',
  Chinroutou: '清老头',
  SuuankouTanki: '四暗刻单骑',
  Suuankou: '四暗刻',
  Daisangen: '大三元',
  Daisuushi: '大四喜',
  Shousuushi: '小四喜',
  Suukantsu: '四杠子',
  Tenhou: '天和',
  Chiihou: '地和',
  Chiitoitsu: '七对子',
  MenzenTsumo: '门前清自摸和',
  DoubleRiichi: '双立直',
  Riichi: '立直',
  Ippatsu: '一发',
  RinshanKaihou: '岭上开花',
  HaiteiRaoyue: '海底捞月',
  HouteiRaoyui: '河底捞鱼',
  Tanyao: '断幺九',
  YakuhaiHaku: '役牌:白',
  YakuhaiHatsu: '役牌:发',
  YakuhaiChun: '役牌:中',
  RoundWind: '场风牌',
  SeatWind: '自风牌',
  Pinfu: '平和',
  Ryanpeikou: '二杯口',
  Iipeikou: '一杯口',
  Toitoi: '对对和',
  Sanankou: '三暗刻',
  Sankantsu: '三杠子',
  Shousangen: '小三元',
  SanshokuDoujun: '三色同顺',
  Ittsu: '一气通贯',
  Chinitsu: '清一色',
  Honitsu: '混一色',
  Honroutou: '混老头',
  Junchan: '纯全带幺九',
  Chanta: '混全带幺九',
  SanshokuDoukou: '三色同刻',
  Dora: '宝牌',
  AkaDora: '红宝牌',
  UraDora: '里宝牌',
};

export function getMahjongYakuLabel(kind: MahjongYakuKind) {
  return mahjongYakuLabels[kind] ?? kind;
}
